"""
Django settings for wolfx_null project.

Generated by 'django-admin startproject' using Django 5.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=v*l(-0qfki=k8eekt^3fnk*trr1+7neq&s*frw)s$lqqz_ua-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "unfold",                           # before django.contrib.admin
    "unfold.contrib.filters",           # optional, if special filters are needed
    "unfold.contrib.forms",             # optional, if special form elements are needed
    "unfold.contrib.import_export",     # optional, if django-import-export package is used
    "unfold.contrib.simple_history",    # optional, if django-simple-history package is used
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_recaptcha',
    'django_cleanup.apps.CleanupConfig',
    'simple_history',
    'import_export',
    
    'web',
]

APPEND_SLASH = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wolfx_null.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'web.context_processor.site_settings',  # Add this line for context processor
            ],
        },
    },
]

WSGI_APPLICATION = 'wolfx_null.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL          =   '/static/'
STATICFILES_DIRS    =   [
    os.path.join(BASE_DIR, 'web/static'),
]
STATIC_ROOT =   os.path.join(BASE_DIR, 'static')
MEDIA_URL   =   '/media/'
MEDIA_ROOT  =   os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ReCaptcha
RECAPTCHA_PRIVATE_KEY       = '*****'
RECAPTCHA_PUBLIC_KEY        = '*****'
RECAPTCHA_DEFAULT_ACTION    = 'generic'
RECAPTCHA_SCORE_THRESHOLD   = 0.7
# RECAPTCHA_LANGUAGE          = 'en' # for auto detection language, remove this from your settings
RECAPTCHA_DISABLE           = False


# Email Setup
DEFAULT_FROM_EMAIL  =   'hello@wolfx.io'
EMAIL_HOST          =   'smtp.zoho.in'
EMAIL_HOST_USER     =   'hello@wolfx.io'
EMAIL_HOST_PASSWORD =   '*******'
EMAIL_PORT          =   587
EMAIL_USE_TLS       =   True
EMAIL_USE_SSL       =   False

# Add the Celery broker URL (this example uses Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# Optionally, add a backend for task results if you need it
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

CELERY_BEAT_SCHEDULE = {
    'auto-upload-social-media-posts': {
        'task': 'web.tasks.auto_upload_social_media_posts',  
        'schedule': 60.0,  # Run the task every 60 seconds
    },
    'auto-create-social-media-posts': {
        'task': 'web.tasks.auto_create_social_media_post',
        'schedule': 300.0 
    }
}


# Django Unfold settings
# settings.py
from django.templatetags.static import static
from django.urls                import reverse_lazy
from django.utils.translation   import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": 'WOLFx Null Admin',
    "SITE_HEADER": 'WOLFx Null Admin',
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    # "SITE_LOGO": lambda request: static("logo.svg"),  # both modes, optimise for 32px height
    "SITE_ICON": {
        "light": lambda request: static("web/img/null_logo.jpeg"),  # light mode
        "dark": lambda request: static("web/img/null_logo.jpeg"),  # dark mode
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "DASHBOARD_CALLBACK": "web.views.dashboard_callback",
    "STYLES": [
        lambda request: static("web/css/style.css"),
    ],
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Social Media Management",
                "items": [
                    {
                        "title": "Social Media Accounts",
                        "icon": "share",  
                        "link": "/admin/web/socialmedia/",
                    },
                    {
                        "title": "Video Script Generator",
                        "icon": "camera",
                        "link": "/admin/web/videoscriptgeneration/",
                    },
                    {
                        "title": "Post",
                        "icon": "article",
                        "link": "/admin/web/post/",
                    },
                    {
                        "title": "Post Schedule",
                        "icon": "schedule",
                        "link": "/admin/web/postschedule/",
                    },
                ],
            },
            {
                "title": ("Main"),
                "items": [
                    {
                        "title": ("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": ("Authentication and Authorization"),
                "separator": True,
                "items": [
                    {
                        "title": ("Users"),
                        "icon": "person",
                        "link": "/admin/auth/user/"
                    },
                    {
                        "title": ("Groups"),
                        "icon": "group",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
            {
                "title": ("Site Configuration"),
                "separator": True,
                "items": [
                    {
                        "title": ("Site Setting"),
                        "icon": "settings",
                        "link": "/admin/web/sitesetting/",
                    },
                ]
            },
            {
                "title": ("Media"),
                "items": [
                    {
                        "title": ("Image Master"),
                        "icon": "image",
                        "link": "/admin/web/imagemaster/",
                    },
                    {
                        "title": ("File Master"),
                        "icon": "attach_file",
                        "link": "/admin/web/filemaster/",
                    },
                ]
            },
            {
                "title": ("Content"),
                "items": [
                    {
                        "title": ("Contact"),
                        "icon": "contact_phone",
                        "link": "/admin/web/contact/",
                    },
                    {
                        "title": ("FAQ Category"),
                        "icon": "help_outline",
                        "link": "/admin/web/faqcategory/",
                    },
                    {
                        "title": ("FAQ"),
                        "icon": "help_outline",
                        "link": "/admin/web/faq/",
                    },
                ]
            },
            {
                "title": ("Case Studies"),
                "items": [
                    {
                        "title": ("Case Study Category"),
                        "icon": "category",
                        "link": "/admin/web/casestudycategory/",
                    },
                    {
                        "title": ("Case Study"),
                        "icon": "article",
                        "link": "/admin/web/casestudy/",
                    },
                    {
                        "title": ("Case Study FAQ"),
                        "icon": "question_answer",
                        "link": "/admin/web/casestudyfaq/",
                    },
                ]
            },
            {
                "title": ("Blog"),
                "items": [
                    {
                        "title": ("Blog Category"),
                        "icon": "category",
                        "link": "/admin/web/blogcategory/",
                    },
                    {
                        "title": ("Blog"),
                        "icon": "article",
                        "link": "/admin/web/blog/",
                    },
                    {
                        "title": ("Blog Image"),
                        "icon": "image",
                        "link": "/admin/web/blogimage/",
                    },
                ]
            },
            {
                "title": ("SEO & Redirects"),
                "items": [
                    {
                        "title": ("Redirect"),
                        "icon": "redo",
                        "link": "/admin/web/redirect/",
                    },
                    {
                        "title": ("Head"),
                        "icon": "manage_search",
                        "link": "/admin/web/head/",
                    },
                ]
            },
        ],
    },
}



