# Generated by Django 4.2.7 on 2025-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_videoscriptgeneration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvideoscriptgeneration',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed content from the blog', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvideoscriptgeneration',
            name='llm_prompt',
            field=models.TextField(blank=True, help_text='Prompt for the LLM to generate a video script', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvideoscriptgeneration',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='videoscriptgeneration',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed content from the blog', null=True),
        ),
        migrations.AlterField(
            model_name='videoscriptgeneration',
            name='llm_prompt',
            field=models.TextField(blank=True, help_text='Prompt for the LLM to generate a video script', null=True),
        ),
        migrations.AlterField(
            model_name='videoscriptgeneration',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
